import Filters from './Filters.jsx';
import './index.less';

import {
	EMPTY_VALUR_FILTER,
	MUL_SELECT_VALUE_FILTER,
	STRING_INPUT_VALUE_FILTER,
	NUMBER_INPUT_VALUE_FILTER,
	NUMBER_INPUT_RANGR_VALUE_FILTER,
	TIME_INPUT_VALUE_FILTER,
	TIME_INPUT_RANGE_VALUE_FILTER
} from './Common.jsx';

Filters.EMPTY_VALUR_FILTER = EMPTY_VALUR_FILTER;
Filters.MUL_SELECT_VALUE_FILTER = MUL_SELECT_VALUE_FILTER;
Filters.STRING_INPUT_VALUE_FILTER = STRING_INPUT_VALUE_FILTER;
Filters.NUMBER_INPUT_VALUE_FILTER = NUMBER_INPUT_VALUE_FILTER;
Filters.NUMBER_INPUT_RANGR_VALUE_FILTER = NUMBER_INPUT_RANGR_VALUE_FILTER;
Filters.TIME_INPUT_VALUE_FILTER = TIME_INPUT_VALUE_FILTER;
Filters.TIME_INPUT_RANGE_VALUE_FILTER = TIME_INPUT_RANGE_VALUE_FILTER;

export default Filters;